routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::middleware(['auth'])->group(function(){

    Route::get('/home', 'HomeController@index')->name('home');
    //Admin
    Route::get('/admin', 'AdminController@index')->name('admin.index');
    //Teacher
    Route::get('/teacher', 'TeacherController@index')->name('teacher.index');
    //Student
    Route::get('/student', 'StudentsController@index')->name('student.index');

    //Test
    Route::get('/test', 'TestsController@index')->name('test.index');
    Route::post('/test/store', 'TestsController@store')->name('test.store');
    Route::post('/test/started', 'TestsController@fetchQuestions')->name('test.fetchQuestions'); //ajax
    Route::post('test/scheduledTest', 'TestsController@schedulingTest')->name('test.schedulingTest');

    //Result
    Route::post('/result', 'ResultController@index')->name('result.index');
    Route::post('/result/clear', 'ResultController@clearSessionAndGoToHome')->name('result.clearAndGo');


    //Subjects
    Route::resource('subjects', 'SubjectsController');
    Route::put('subjects/{subject}/edit', 'SubjectsController@edit')->name('subject.edit');
    Route::put('subjects/{subject}/update', 'SubjectsController@update')->name('subject.update');
    Route::get('/manage-subjects', 'SubjectsController@manage')->name('subject.manage');

    //Chapters
    Route::resource('chapters', 'ChaptersController');
    Route::put('subjects/{subject}/chapters', 'ChaptersController@index')->name('chapter.index');
    Route::get('chapters/{chapter}/edit', 'ChaptersController@edit')->name('chapter.edit');
    Route::put('chapters/{chapter}/update', 'ChaptersController@update')->name('chapter.update');
    Route::put('chapters/{subject}/create', 'ChaptersController@create')->name('chapter.create');
    Route::get('/chapters', 'ChaptersController@manage')->name('chapter.manage');

    //Questions
    Route::resource('questions', 'QuestionsController');
    Route::get('questions/chapters/{subject}', 'QuestionsController@getChapters'); // for ajax
    Route::get('questions/{question}/edit', 'QuestionsController@edit')->name('question.edit');
    Route::post('questions/{question}/update', 'QuestionsController@update')->name('question.update');
    Route::get('chapters/{chapter}/{subject}', 'QuestionsController@index_specific')->name('question.index_specific');
    Route::put('questions/create/{subject}/{chapter}', 'QuestionsController@create')->name('question.create');

    //options
    Route::resource('options', 'OptionsController');
    Route::post('/options/correct', 'OptionsController@selectCorrectOption')->name('options.selectCorrect');

    //solution
    Route::post('/test/solution', 'SolutionController@index')->name('solution.index');
});

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Question extends Model
{
    protected $fillable = [
        'question',
        'subject_id',
        'chapter_id',
        'difficulty_level',
        'marks'
    ];

    public function options()
    {
        return $this->hasMany(Option::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use App\Subject;
use App\Chapter;
use App\Option;
use Illuminate\Http\Request;

class QuestionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = Question::all();

        return view('question.index', compact([
            'questions'
        ]));
    }

    public function index_specific(Request $request, Chapter $chapter, Subject $subject)
    {
        // dd($chapter);
        $questions = Question::where([
            'chapter_id'=>$chapter->id,
            'subject_id'=>$subject->id
        ])->get();
        // $chapter = $chapter;
        // $subject = $subject;
        return view('question.index', compact([
            'questions',
            'chapter',
            'subject'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request, Subject $subject, Chapter $chapter)
    {
        // $subject =  $request->subject;
        // $chapter = $request->chapter;
        return view('question.create', compact([
            'subject',
            'chapter'
        ]));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    //    dd($request->optionRadios);
        $question = Question::create([
            'question'=>$request->question,
            'chapter_id'=>$request->chapters[0],
            'subject_id'=>$request->subjects[0],
            'marks'=>$request->marks,
            'difficulty_level'=>$request->difficulty_level[0]
        ]);

        // dd($question);

        $option1 = Option::create([
            'question_id'=>$question->id,
            'subject_id'=>$request->subjects[0],
            'chapter_id'=>$request->chapters[0],
            'option'=>$request->option1
        ]);
        $option2 = Option::create([
            'question_id'=>$question->id,
            'subject_id'=>$request->subjects[0],
            'chapter_id'=>$request->chapters[0],
            'option'=>$request->option2
        ]);
        $option3 = Option::create([
            'question_id'=>$question->id,
            'subject_id'=>$request->subjects[0],
            'chapter_id'=>$request->chapters[0],
            'option'=>$request->option3
        ]);
        $option4 = Option::create([
            'question_id'=>$question->id,
            'subject_id'=>$request->subjects[0],
            'chapter_id'=>$request->chapters[0],
            'option'=>$request->option4
        ]);

        if($request->optionRadios == 1)
        {
            Option::where('id',$option1->id)->update(['correct'=> 1]);
        }
        else if($request->optionRadios == 2)
        {
            Option::where('id',$option2->id)->update(['correct'=> 1]);
        }
        else if($request->optionRadios == 3)
        {
            Option::where('id',$option3->id)->update(['correct'=> 1]);
        }
        else if($request->optionRadios == 4)
        {
            Option::where('id',$option4->id)->update(['correct'=> 1]);
        }


        session()->flash('success', "Question Added Successfully");
        return redirect(route('subjects.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        // dd($question);
        $subject = Subject::where('id', $question->subject_id)->first();
        $chapter = Chapter::where('id', $question->chapter_id)->first();
        $options = Option::where('question_id', $question->id)->get();

        // dd($options);
        
        return view('question.edit', compact([
            'question',
            'subject',
            'chapter',
            'options'
        ]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question)
    {
        $question->update([
            'question'=>$request->question,
            'marks'=> $request->marks,
            'difficulty_level'=> $request->difficulty_level[0]
        ]);

        $option1 = (int)$request->option1_id;
        $option2 =(int) $request->option2_id;
        $option3 = (int)$request->option3_id;
        $option4 = (int)$request->option4_id;

        if($request->optionRadios == 1)
        {
            Option::where('id',$option1)->update([
                'correct'=> 1,
                'option'=>$request->option1
            ]);

            Option::where('id',$option2)->update(['correct'=> 0]);
            Option::where('id',$option3)->update(['correct'=> 0]);
            Option::where('id',$option4)->update(['correct'=> 0]);
        }
        else if($request->optionRadios == 2)
        {
            Option::where('id',$option2)->update([
                'correct'=> 1,
                'option'=>$request->option2
            ]);
            Option::where('id',$option1)->update(['correct'=> 0]);
            Option::where('id',$option3)->update(['correct'=> 0]);
            Option::where('id',$option4)->update(['correct'=> 0]);
        }
        else if($request->optionRadios == 3)
        {
            Option::where('id',$option3)->update([
                'correct'=> 1,
                'option'=>$request->option3
            ]);
            Option::where('id',$option1)->update(['correct'=> 0]);
            Option::where('id',$option2)->update(['correct'=> 0]);
            Option::where('id',$option4)->update(['correct'=> 0]);
        }
        else if($request->optionRadios == 4)
        {
            Option::where('id',$option4)->update([
                'correct'=> 1,
                'option'=>$request->option4
            ]);
            Option::where('id',$option1)->update(['correct'=> 0]);
            Option::where('id',$option2)->update(['correct'=> 0]);
            Option::where('id',$option3)->update(['correct'=> 0]);
        }
        session()->flash('success', "Subject has been updated successfully!");
        return redirect(route('question.index_specific', [$question->chapter_id, $question->subject_id]));
    }

    public function destroy(Question $question)
    {
        //
    }

    public function getChapters(Request $request, $id)
    {
        // dd("got it !");
        $chapters = Chapter::where('subject_id', $id)->get();
        echo json_encode($chapters);
    }
}

resources/views/question/create.blade.php
@extends('layouts.app')
@section('title','MSBTE | Teacher')

@section('content')

<div class="container">

    <div class="row">
        <div class="col-md-12">
            <!-- Breadcrumb -->
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('teacher.index') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('subjects.index') }}">Subjects</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('subjects.show', $subject->id) }}">{{ $subject->name }}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Questions</li>
                </ol>
            </nav>
        </div>

        <div class="col-md-12">
            <!-- Page Heading -->
            <div class="heading">
                <h3>Add Question</h3>
            </div>
        </div>

        <div class="col-md-12">
            <form action="{{ route('questions.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="name">Subject Name</label>
                    <select name="subjects[]" class="form-control subject_select " readonly>
                    <!-- <option disabled selected>Select Subject</option> -->

                        <option value="{{ $subject->id }}" > {{ $subject->name }} </option>

                    </select>
                </div>
                <div class="form-group">
                    <label for="name">Chapter Name</label>
                    <select name="chapters[]" class="form-control chapter_select " readonly>
                        <!-- <option disabled selected>Select Chapter</option> -->
                        <option value="{{ $chapter->id }}" > {{ $chapter->name }} </option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="name">Question</label>
                    <input type="text"
                           id="question"
                           name="question"
                           placeholder="Enter question"
                           value = "{{ old('question') }}"
                           class="form-control {{ $errors->has('question') ? 'is-invalid' : '' }}">
                    @error('question')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="marks">Marks</label>
                    <input type="text"
                           id="marks"
                           name="marks"
                           placeholder="Enter Marks"
                           value = "{{ old('marks') }}"
                           class="form-control {{ $errors->has('marks') ? 'is-invalid' : '' }}">
                    @error('marks')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="name">Difficulty Level</label>
                    <select name="difficulty_level[]" class="form-control difficulty_select ">
                        <option disabled selected>Select DIfficulty level</option>
                        <option value="easy">Easy</option>
                        <option value="medium">Medium</option>
                        <option value="hard">Hard</option>
                    </select>
                </div>
                <!-- options -->

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-10">
                            <label for="name">Option 1</label>
                            <input type="text"
                                id="option1"
                                name="option1"
                                placeholder="Enter Option 1"
                                value = "{{ old('option1') }}"
                                class="form-control {{ $errors->has('option1') ? 'is-invalid' : '' }}">
                            @error('option1')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="col-md-2 p-4">
                            <input class="form-check-input"  name="optionRadios" type="radio" value="1" id="radio1">
                            <label class="form-check-label" for="radio1">
                                Correct
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-10">
                            <label for="name">Option 2</label>
                            <input type="text"
                                id="option2"
                                name="option2"
                                placeholder="Enter Option 2"
                                value = "{{ old('option2') }}"
                                class="form-control {{ $errors->has('option2') ? 'is-invalid' : '' }}">
                            @error('option2')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="col-md-2 p-4">
                            <input class="form-check-input" name="optionRadios"  type="radio" value="2" id="radio2">
                            <label class="form-check-label" for="radio2">
                                Correct
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-10">
                            <label for="name">Option 3</label>
                            <input type="text"
                                id="option3"
                                name="option3"
                                placeholder="Enter Option 3"
                                value = "{{ old('option3') }}"
                                class="form-control {{ $errors->has('option3') ? 'is-invalid' : '' }}">
                            @error('option3')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="col-md-2 p-4">
                            <input class="form-check-input" name="optionRadios"  type="radio" value="3" id="radio3">
                            <label class="form-check-label" for="radio3">
                                Correct
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-10">
                            <label for="name">Option 4</label>
                            <input type="text"
                                id="option4"
                                name="option4"
                                placeholder="Enter Option 4"
                                value = "{{ old('option4') }}"
                                class="form-control {{ $errors->has('option4') ? 'is-invalid' : '' }}">
                            @error('option4')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="col-md-2 p-4">
                            <input class="form-check-input" name="optionRadios"  type="radio" value="4" id="radio4">
                            <label class="form-check-label" for="radio4">
                                Correct
                            </label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-outline-success">Add Question</button>
                </div>
            </form>
        </div>
    </div>

</div>
@endsection

resources/views/question/index.blade.php
@extends('layouts.app')
@section('title','MCQ-App | Teacher')


@section('content')

<div class="container">

    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('teacher.index') }}">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('subjects.index') }}">Subjects</a></li>
            <li class="breadcrumb-item"><a href="{{ route('subjects.show', $subject->id) }}">{{ $subject->name }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Questions</li>
        </ol>
    </nav>

    <!-- Page Heading -->
    <div class="heading">
        <form action="{{ route('question.create', [$subject, $chapter]) }}" method="POST">
            @csrf
            @method('PUT')
            <h3 class="d-inline-block">All Questions</h3>
            <button type="submit" class="btn btn-primary text-white float-right">
                <span class="fas fa-plus"></span> Add Question
            </button>
        </form>
    </div>

    <table class="table table-bordered" id="manage-questions-table">
        <thead>
            <tr>
                <th>Question</th>
                <th>Marks</th>
                <th>Difficulty Level</th>
                <th>Subject</th>
                <th>Chapter</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach($questions as $question)
            <?php
                $subject = App\Subject::where('id', $question->subject_id)->get()[0];
                $chapter = App\Chapter::where('id', $question->chapter_id)->get()[0];
            ?>
            <tr class="{{ $question->id }}">
                <td>{{$question->question}}</td>
                <td>{{$question->marks}}</td>
                <td>{{$question->difficulty_level}}</td>
                <td>{{$subject->name}}</td>
                <td>{{$chapter->name}}</td>
                <td>
                    <button class="btn btn-sm btn-primary" data-info="">
                        <span class=""></span> View
                    </button>
                    <!-- <button class="edit-modal btn btn-sm btn-secondary" data-info="">
                        <span class=""></span> Edit
                    </button> -->
                    <a href="{{ route('question.edit', $question->id) }}" class="btn edit-modal btn btn-sm btn-secondary">
                        Edit
                    </a>
                    <button class="delete-modal btn btn-sm btn-danger" data-info="">
                        <span class=""></span> Delete
                    </button>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

</div>
@endsection

@section('page-level-scripts')

@endsection