routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::middleware(['auth'])->group(function(){

    Route::get('/home', 'HomeController@index')->name('home');
    //Admin
    Route::get('/admin', 'AdminController@index')->name('admin.index');
    //Teacher
    Route::get('/teacher', 'TeacherController@index')->name('teacher.index');
    //Student
    Route::get('/student', 'StudentsController@index')->name('student.index');

    //Test
    Route::get('/test', 'TestsController@index')->name('test.index');
    Route::post('/test/store', 'TestsController@store')->name('test.store');
    Route::post('/test/started', 'TestsController@fetchQuestions')->name('test.fetchQuestions'); //ajax
    Route::post('test/scheduledTest', 'TestsController@schedulingTest')->name('test.schedulingTest');

    //Result
    Route::post('/result', 'ResultController@index')->name('result.index');
    Route::post('/result/clear', 'ResultController@clearSessionAndGoToHome')->name('result.clearAndGo');


    //Subjects
    Route::resource('subjects', 'SubjectsController');
    Route::put('subjects/{subject}/edit', 'SubjectsController@edit')->name('subject.edit');
    Route::put('subjects/{subject}/update', 'SubjectsController@update')->name('subject.update');
    Route::get('/manage-subjects', 'SubjectsController@manage')->name('subject.manage');

    //Chapters
    Route::resource('chapters', 'ChaptersController');
    Route::put('subjects/{subject}/chapters', 'ChaptersController@index')->name('chapter.index');
    Route::get('chapters/{chapter}/edit', 'ChaptersController@edit')->name('chapter.edit');
    Route::put('chapters/{chapter}/update', 'ChaptersController@update')->name('chapter.update');
    Route::put('chapters/{subject}/create', 'ChaptersController@create')->name('chapter.create');
    Route::get('/chapters', 'ChaptersController@manage')->name('chapter.manage');

    //Questions
    Route::resource('questions', 'QuestionsController');
    Route::get('questions/chapters/{subject}', 'QuestionsController@getChapters'); // for ajax
    Route::get('questions/{question}/edit', 'QuestionsController@edit')->name('question.edit');
    Route::post('questions/{question}/update', 'QuestionsController@update')->name('question.update');
    Route::get('chapters/{chapter}/{subject}', 'QuestionsController@index_specific')->name('question.index_specific');
    Route::put('questions/create/{subject}/{chapter}', 'QuestionsController@create')->name('question.create');

    //options
    Route::resource('options', 'OptionsController');
    Route::post('/options/correct', 'OptionsController@selectCorrectOption')->name('options.selectCorrect');

    //solution
    Route::post('/test/solution', 'SolutionController@index')->name('solution.index');
});

app/Subject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    protected $fillable = [
        'name'
    ];
}

app/Http/Controllers/SubjectsController.php
<?php

namespace App\Http\Controllers;

use App\Chapter;
use App\Subject;
use Illuminate\Http\Request;

class SubjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subjects = Subject::all();
        return view('subject.index', compact([
            'subjects'
        ]));
    }

    public function manage()
    {
        $subjects = Subject::all();
        return view('subject.manage', compact([
            'subjects'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('subject.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Subject::create([
            'name'=>$request->name
        ]);

        session()->flash('success', "Subject Added Successfully");
        return redirect(route('subjects.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function show(Subject $subject)
    {
        $subject = Subject::where('id', $subject->id)->get()[0];
        $chapters = Chapter::where('subject_id', $subject->id)->get();
        return view('subject.show', compact([
            'subject',
            'chapters'
        ]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function edit(Subject $subject)
    {

        $subject = Subject::where('id', $subject->id)->get()[0];
        // dd($subject);

        return view('subject.edit', compact([
            'subject'
        ]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Subject $subject)
    {
        // dd($subject);

        $subject->update([
            'name'=>$request->name
        ]);
        session()->flash('success', "Subject has been updated successfully!");
        return redirect(route('subjects.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function destroy(Subject $subject)
    {
        //
    }
}

resources/views/subject/create.blade.php
@extends('layouts.admin')
@section('title','MCQ-App | Admin')

@section('subjects','active')
@section('subjects-show','show')
@section('subject-create','active')

@section('main-content')

<div class="container">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between">
        <h1 class="h3 mb-4 text-gray-800">Subject</h1>
        <a href="" class="d-none d-sm-inline-nlock btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-list-ul fa-sm text-white"></i>
        </a>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><h3>Create Subject</h3></div>
                <div class="card-body">
                    <form action="{{ route('subjects.store') }}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="name">Subject Name</label>
                            <input type="text"
                                    id="name"
                                    name="name"
                                    placeholder="Enter Name"
                                    value = "{{ old('name') }}"
                                    class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}">
                            @error('name')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-success">Add Subject</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


</div>
@endsection

resources/views/subject/edit.blade.php
@extends('layouts.layout')
@section('title','MCQ-App | Admin')

@section('main-content')

<div class="container mt-4 mx-2">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between">
        <h1 class="h3 mb-4 text-gray-800">Subject</h1>
        <a href="" class="d-none d-sm-inline-nlock btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-list-ul fa-sm text-white"></i>
        </a>                  
    </div>
  
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h3>Update Subject</span></h3></div>
                    <div class="card-body">
                        <form action="{{ route('subjects.update', $subject->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="name">Subject Name</label>
                                <input type="text"
                                       id="name"
                                       name="name"
                                       placeholder="Enter Name"
                                       value = "{{ $subject->name }}"
                                       class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}">
                                @error('name')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-success">Update Subject</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

      
</div>
@endsection

resources/views/subject/index.blade.php
@extends('layouts.app')
@section('title','MCQ-App | Teacher')

@section('content')

<div class="container">

    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('teacher.index') }}">Home</a></li>
            <li class="breadcrumb-item" aria-current="page">Subjects</li>
        </ol>
    </nav>

    <!-- Page Heading -->
    <div class="heading">
        <h3>Subjects</h3>
    </div>

    <div class="row">
        @foreach($subjects as $subject)
            <div class="col-sm-4">
                <div id="subject-card" class="card border-primary text-center">
                    <div class="card-body text-primary">
                        <a href="{{ route('subjects.show', $subject->id) }}" class="stretched-link"><h5 class="card-title">{{ $subject->name }}</h5></a>
                    </div>
                </div>
            </div>
        @endforeach
    </div>

</div>
@endsection

resources/views/subject/manage.blade.php
@extends('layouts.admin')
@section('title','MCQ-App | Admin')

@section('subjects','active')
@section('subjects-show','show')
@section('subject-manage','active')

@section('main-content')

<div class="container">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">All Subjects</h1>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Subjects</h6>
        </div>
        <div class="card-body">
            <div id="export-buttons" class="float-right"></div>
            <table class="table table-hover table-bordered">
                <thead class="thead-primary">
                    <tr>
                        <th scope="col">Sr. No.</th>
                        <th scope="col">Name</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($subjects as $subject)
                        <tr>
                            <th scope="row">{{ $subject->id }}</th>
                            <td>{{ $subject->name }}</td>
                            <td class="mr-3">
                                <button class="btn btn-primary"><i class="fas fa-pen"></i> Edit</button>
                                <button class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

</div>
@endsection

resources/views/subject/show.blade.php
@extends('layouts.app')
@section('title','MCQ-App | Teacher')

@section('content')

<div class="container">
    <div class="chapters-list">
        <div class="row">
            <div class="col-md-12">

                <!-- Breadcrumb -->
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('teacher.index') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('subjects.index') }}">Subjects</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{{ $subject->name }}</li>
                    </ol>
                </nav>

                <!-- Page Heading -->
                <div class="heading">
                    <h3>{{ $subject->name }}</h3>
                </div>

                @if (auth()->user()->isStudent())
                
                @endif

                <form action="{{ route('test.store') }}" method="POST">
                    @csrf
                    <table class="table">
                        <tbody>
                            <input type="text"value="{{ $chapters[0]->subject_id }}" name="subject_id" hidden>
                            @foreach($chapters as $chapter)
                                <tr>
                                    <td>
                                        {{ $chapter->name }}
                                        @if (auth()->user()->role == "teacher")
                                            <a href="{{ route('question.index_specific', [$chapter->id, $subject->id]) }}" class="btn btn-primary btn-sm text-white float-right ml-4">
                                                <span class="fas fa-eye"></span> View All Questions
                                            </a>
                                        @endif
                                        
                                        <div class="form-check float-right" id="outer">
                                            <input class="form-check-input checkbox" type="checkbox" name="checkbox_{{$chapter->id}}" id="checkbox_{{$chapter->id}}" onclick="getSelectedCheckBox()">
                                            <input class="form-control weightAge" id="{{$chapter->id}}" name="{{$chapter->id}}" type="number" value="0" style="display: none;"  onclick="marksChanged()" oninput="marksChanged()" min=0>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="form-group">
                        <label for="totalMarks">Total Marks</label>
                        <input type="number" class="form-control" name="totalMarks" id="totalMarks" value="0" readonly>
                    </div>

                    @if (auth()->user()->isTeacher())
                        <div class="form-group">
                            <label for="scheduleDate">Schedule On</label>
                            <input type="datetime-local" class="form-control" name="scheduleDate" id="scheduleDate">
                        </div>
                    @endif

                    <button type="submit" class="btn btn-primary text-white submitBtn" id="StartTestBtn">
                        <span class="fas fa-eye"></span>
                        @if (auth()->user()->isTeacher())
                            Schedule Test
                        @else
                            Start Practise Test
                        @endif

                    </button>
                </form>
               

            </div>
        </div>
    </div>
</div>
@endsection

@section('page-level-scripts')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>

    document.getElementById('StartTestBtn').disabled = true;

    var total_field = document.getElementById('totalMarks')
    var checkboxes = document.getElementsByClassName('checkbox');
    var weightAges = document.getElementsByClassName('weightAge');
    var checkBoxSelected = 0;
    var sum = 0;
function getSelectedCheckBox(){
    var selected = [];
    for (var i=0; i<checkboxes.length; i++) {
        if (checkboxes[i].checked) {
            selected.push(checkboxes[i].id);
            weightAges[i].style.display = 'inline-block';
        }else{
            weightAges[i].style.display = 'none';
        }
        checkBoxSelected = selected.length;
    }

    for(var j=0; j<selected.length;j++)
    {
        // console.log(selected[j]);
        var x = selected[j].split("_")[1];
        console.log("id = "+x);

        var marks_ele = document.getElementById(x);
        console.log("marks = "+ marks_ele.value);
    }
    checkSubmitBtn();
}
$("input:checkbox.checkbox").click(function() {
    var ele_id;
    if(!$(this).is(":checked"))
    {
        ele_id = this.id;
        var x = ele_id.split("_")[1];
        var marks_ele = document.getElementById(x);
        console.log("sum: "+sum);
        sum -= parseInt(marks_ele.value);
        marks_ele.value = 0;
        total_field.value = "";
        total_field.value = sum;

        // alert('you are unchecked ' + marks_ele.value);
    }
    checkSubmitBtn();
});

function marksChanged(){

    var selected = [];
    for (var i=0; i<checkboxes.length; i++) {
        if (checkboxes[i].checked) {
            selected.push(checkboxes[i].id);
            weightAges[i].style.display = 'inline-block';
        }else{
            weightAges[i].style.display = 'none';
            console.log("Unchecked !");
        }
        checkBoxSelected = selected.length;
    }

    sum = 0;
    for(var k=0; k<checkBoxSelected;k++){
        var id = selected[k].split("_")[1];
        // console.log("length = "+selected.length);
        var marks_ele = document.getElementById(id);
        console.log("marks = "+marks_ele.value);
        if(marks_ele.value != "")
            sum += parseInt(marks_ele.value);
    }
    total_field.value = "";
    console.log("sum = "+sum);
    total_field.value = sum;
    checkSubmitBtn();
}

function checkSubmitBtn(){
    var submitBtn = document.getElementById('StartTestBtn');
    if(total_field.value != "0")
    {
        console.log("-----Checking--------");
        submitBtn.disabled  = false;
        console.log("do false");
    }else{
        submitBtn.disabled  = true;
        console.log("do true");
    }
    console.log("Total marks == "+total_field.value);
}



</script>

@endsection