routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::middleware(['auth'])->group(function(){

    Route::get('/home', 'HomeController@index')->name('home');
    //Admin
    Route::get('/admin', 'AdminController@index')->name('admin.index');
    //Teacher
    Route::get('/teacher', 'TeacherController@index')->name('teacher.index');
    //Student
    Route::get('/student', 'StudentsController@index')->name('student.index');

    //Test
    Route::get('/test', 'TestsController@index')->name('test.index');
    Route::post('/test/store', 'TestsController@store')->name('test.store');
    Route::post('/test/started', 'TestsController@fetchQuestions')->name('test.fetchQuestions'); //ajax
    Route::post('test/scheduledTest', 'TestsController@schedulingTest')->name('test.schedulingTest');

    //Result
    Route::post('/result', 'ResultController@index')->name('result.index');
    Route::post('/result/clear', 'ResultController@clearSessionAndGoToHome')->name('result.clearAndGo');


    //Subjects
    Route::resource('subjects', 'SubjectsController');
    Route::put('subjects/{subject}/edit', 'SubjectsController@edit')->name('subject.edit');
    Route::put('subjects/{subject}/update', 'SubjectsController@update')->name('subject.update');
    Route::get('/manage-subjects', 'SubjectsController@manage')->name('subject.manage');

    //Chapters
    Route::resource('chapters', 'ChaptersController');
    Route::put('subjects/{subject}/chapters', 'ChaptersController@index')->name('chapter.index');
    Route::get('chapters/{chapter}/edit', 'ChaptersController@edit')->name('chapter.edit');
    Route::put('chapters/{chapter}/update', 'ChaptersController@update')->name('chapter.update');
    Route::put('chapters/{subject}/create', 'ChaptersController@create')->name('chapter.create');
    Route::get('/chapters', 'ChaptersController@manage')->name('chapter.manage');

    //Questions
    Route::resource('questions', 'QuestionsController');
    Route::get('questions/chapters/{subject}', 'QuestionsController@getChapters'); // for ajax
    Route::get('questions/{question}/edit', 'QuestionsController@edit')->name('question.edit');
    Route::post('questions/{question}/update', 'QuestionsController@update')->name('question.update');
    Route::get('chapters/{chapter}/{subject}', 'QuestionsController@index_specific')->name('question.index_specific');
    Route::put('questions/create/{subject}/{chapter}', 'QuestionsController@create')->name('question.create');

    //options
    Route::resource('options', 'OptionsController');
    Route::post('/options/correct', 'OptionsController@selectCorrectOption')->name('options.selectCorrect');

    //solution
    Route::post('/test/solution', 'SolutionController@index')->name('solution.index');
});

app/Chapter.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Chapter extends Model
{
    protected $fillable = [
        'name',
        'subject_id'
    ];
}

app/Http/Controllers/ChaptersController.php
<?php

namespace App\Http\Controllers;

use App\Chapter;
use App\Subject;
use Illuminate\Http\Request;

class ChaptersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, Subject $subject)
    {
        // dd($subject->id);
        $chapters = Chapter::where('subject_id', $subject->id)->get();
        $subject_id = $subject->id;

        return view('chapter.index', compact([
            'chapters',
            'subject_id'
        ]));
    }

    public function manage()
    {
        $chapters = Chapter::all();
        return view('chapter.manage', compact([
            'chapters'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request, Subject $subject)
    {
        // dd($subject);
        // $subject = Subject::all();
        return view('chapter.create', compact([
            'subject'
        ]));

        session()->flash('success', "Chapter Added Successfully");
        return redirect()->back();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->subjects[0]);
        Chapter::create([
            'name'=> $request->name,
            'subject_id'=> $request->subjects[0]
        ]);
        session()->flash('success', "Chapter Added Successfully");
        return redirect(route('subjects.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Chapter  $chapter
     * @return \Illuminate\Http\Response
     */
    public function show(Chapter $chapter)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Chapter  $chapter
     * @return \Illuminate\Http\Response
     */
    public function edit(Chapter $chapter)
    {
        // dd($chapter);
        $chapter = Chapter::where('id', $chapter->id)->get()[0];
        // dd($chapter);

        return view('chapter.edit', compact([
            'chapter'
        ]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Chapter  $chapter
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Chapter $chapter)
    {
        // dd($chapter);
        $chapter->update([
            'name'=>$request->name
        ]);
        session()->flash('success', "Chapter has been updated successfully!");
        return redirect(route('subjects.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Chapter  $chapter
     * @return \Illuminate\Http\Response
     */
    public function destroy(Chapter $chapter)
    {
        //
    }
}

resources/views/chapter/create.blade.php
@extends('layouts.admin')
@section('title','MCQ-App | Admin')

@section('chapters','active')
@section('chapters-show','show')
@section('chapter-create','active')

@section('content')

<div class="container">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between">
        <h1 class="h3 mb-4 text-gray-800">Chapter</h1>
        <a href="" class="d-none d-sm-inline-nlock btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-list-ul fa-sm text-white"></i>
        </a>
    </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h3>Create Chapter</h3></div>
                    <div class="card-body">
                        <form action="{{ route('chapters.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="name">Subject Name</label>

                                <select name="subjects[]" class="form-control subject_select ">
                                    <option value="{{ $subject->id }}" > {{ $subject->name }} </option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="name">Chapter Name</label>
                                <input type="text"
                                       id="name"
                                       name="name"
                                       placeholder="Enter Chapter Name"
                                       value = "{{ old('name') }}"
                                       class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}">
                                @error('name')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-success">Add Chapter</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>


</div>
@endsection

resources/views/chapter/edit.blade.php
@extends('layouts.layout')
@section('title','MCQ-App | Admin')

@section('main-content')

<div class="container mt-4 mx-2">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between">
        <h1 class="h3 mb-4 text-gray-800">Chapter</h1>
        <a href="" class="d-none d-sm-inline-nlock btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-list-ul fa-sm text-white"></i>
        </a>                  
    </div>
  
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h3>Update Chapter</span></h3></div>
                    <div class="card-body">
                        <form action="{{ route('chapter.update', $chapter->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="name">Chapter Name</label>
                                <input type="text"
                                       id="name"
                                       name="name"
                                       placeholder="Enter Name"
                                       value = "{{ $chapter->name }}"
                                       class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}">
                                @error('name')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-success">Update Chapter</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

      
</div>
@endsection

resources/views/chapter/index.blade.php
@extends('layouts.layout')
@section('title','MCQ-App | Admin')

@section('main-content')

<div class="container mt-4 mx-2">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between">
        <h1 class="h3 mb-4 text-gray-800">All chapters</h1>
        <a href="" class="d-none d-sm-inline-nlock btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-list-ul fa-sm text-white"></i>
        </a>
    </div>

    <!-- Add Chapter -->
    <form action="{{ route('chapter.create', $subject_id) }}" method="POST">
        @csrf
        @method('PUT')
        <button type="submit" class="btn btn-link btn-primary text-white my-3">
            <span class="fas fa-plus"></span>
             Add Chapter
        </button>
    </form>

</div>
@endsection

resources/views/chapter/manage.blade.php
@extends('layouts.admin')
@section('title','MCQ-App | Admin')

@section('chapters','active')
@section('chapters-show','show')
@section('chapter-manage','active')

@section('content')

<div class="container">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">All Chapters</h1>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Chapters</h6>
        </div>
        <div class="card-body">
            <div id="export-buttons" class="float-right"></div>
            <table class="table table-hover table-bordered">
                <thead class="thead-primary">
                    <tr>
                        <th scope="col">Sr. No.</th>
                        <th scope="col">Name</th>
                        <th scope="col">Subject</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($chapters as $chapter)
                        <tr>
                            <th scope="row">{{ $chapter->id }}</th>
                            <td>{{ $chapter->name }}</td>

                            <td>{{ $chapter->subject_id }}</td>

                            <td class="mr-3">
                                <button class="btn btn-primary"><i class="fas fa-pen"></i> Edit</button>
                                <button class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

</div>
@endsection